name: general
on: [push, pull_request]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container: maierbn/opendihu:latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          path: opendihu
      - name: Build 
        working-directory: opendihu
        run: python3 dependencies/scons/scons.py BUILD_TYPE=RELEASE

